#!/usr/bin/env python3
"""Retrain the centre detector on CD-crop data that matches inference exactly.

Training data is generated by prepare_center_training_data.py — each image is a
155×123 CD crop (centered on OBB) resized-with-pad to 224×224, with labels in
CD-crop-relative normalized [0,1] coordinates.

This matches the firmware's FillInputFromCrop + centre detector pipeline one-to-one.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import keras
import numpy as np
import tensorflow as tf

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

IMAGE_HEIGHT = 224
IMAGE_WIDTH = 224
BATCH_SIZE = 16
EPOCHS_HEAD = 80
EPOCHS_FULL = 40
LEARNING_RATE = 3e-5
PATIENCE = 15

BASE_MODEL_PATH = (
    PROJECT_ROOT
    / "artifacts"
    / "training"
    / "center_model_20260531_193518"
    / "best_model.keras"
)
DATA_DIR = PROJECT_ROOT / "data" / "center_training_crops"
RUN_DIR = PROJECT_ROOT / "artifacts" / "training" / "center_model_v4_cdcrop"


def _augment(image: tf.Tensor, label: tf.Tensor) -> tuple[tf.Tensor, tf.Tensor]:
    image = tf.image.random_brightness(image, max_delta=0.20)
    image = tf.image.random_contrast(image, lower=0.6, upper=1.4)
    image = tf.image.random_saturation(image, lower=0.7, upper=1.3)
    image = tf.image.random_hue(image, max_delta=0.08)

    angle_rad = tf.random.uniform([], -0.04, 0.04)
    c = tf.cos(angle_rad)
    s = tf.sin(angle_rad)
    cx_img = tf.constant(IMAGE_WIDTH / 2.0, tf.float32)
    cy_img = tf.constant(IMAGE_HEIGHT / 2.0, tf.float32)
    tx = (1.0 - c) * cx_img + s * cy_img
    ty = -s * cx_img + (1.0 - c) * cy_img
    transform = [c, -s, tx, s, c, ty, 0.0, 0.0]
    image = tf.raw_ops.ImageProjectiveTransformV3(
        images=tf.expand_dims(image, 0),
        transforms=tf.expand_dims(transform, 0),
        output_shape=[IMAGE_HEIGHT, IMAGE_WIDTH],
        fill_value=128,
        interpolation="BILINEAR",
    )[0]

    lx = label[0] * tf.constant(IMAGE_WIDTH, tf.float32) - cx_img
    ly = label[1] * tf.constant(IMAGE_HEIGHT, tf.float32) - cy_img
    lx_rot = c * lx - s * ly
    ly_rot = s * lx + c * ly
    label = tf.stack([
        (lx_rot + cx_img) / tf.constant(IMAGE_WIDTH, tf.float32),
        (ly_rot + cy_img) / tf.constant(IMAGE_HEIGHT, tf.float32),
    ])

    image = tf.clip_by_value(image, 0.0, 255.0)
    return image, label


def build_dataset(
    entries: list[dict],
    augment: bool = False,
    shuffle: bool = False,
) -> tf.data.Dataset:
    paths = [str(DATA_DIR / e["image_path"]) for e in entries]
    labels_arr = np.array([
        [float(e["center_x_norm"]), float(e["center_y_norm"])]
        for e in entries
    ], dtype=np.float32)

    def _gen():
        for p, lbl in zip(paths, labels_arr):
            yield p, lbl

    ds = tf.data.Dataset.from_generator(
        _gen, output_types=(tf.string, tf.float32), output_shapes=((), (2,)),
    )

    def _load(path, lbl):
        img = tf.io.read_file(path)
        img = tf.image.decode_png(img, channels=3)
        img = tf.image.resize(img, [IMAGE_HEIGHT, IMAGE_WIDTH])
        img = tf.cast(img, tf.float32)
        return img, lbl

    ds = ds.map(_load, num_parallel_calls=tf.data.AUTOTUNE)
    if augment:
        ds = ds.map(_augment, num_parallel_calls=tf.data.AUTOTUNE)
    if shuffle:
        ds = ds.shuffle(512)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds


def main() -> None:
    os.makedirs(str(RUN_DIR), exist_ok=True)

    with open(DATA_DIR / "metadata.json") as f:
        all_entries = json.load(f)

    train_entries = [e for e in all_entries if e["split"] in ("train",)]
    val_entries = [e for e in all_entries if e["split"] == "val"]

    # Include all board entries in training
    board_entries = [e for e in all_entries if e["source"] == "board"]
    for e in board_entries:
        if e not in train_entries:
            train_entries.append(e)

    print(f"Train: {len(train_entries)} (board: {len(board_entries)})")
    print(f"Val:   {len(val_entries)}")

    train_ds = build_dataset(train_entries, augment=True, shuffle=True)
    val_ds = build_dataset(val_entries)

    model = keras.models.load_model(str(BASE_MODEL_PATH))
    print(f"Loaded base model: {BASE_MODEL_PATH}")

    for layer in model.layers:
        if "mobilenetv2" in layer.name:
            layer.trainable = False
            print(f"  Frozen: {layer.name}")

    model.compile(
        optimizer=keras.optimizers.Adam(LEARNING_RATE),
        loss=keras.losses.MeanSquaredError(),
        metrics=[keras.metrics.MeanAbsoluteError(name="mae")],
    )

    callbacks = [
        keras.callbacks.ModelCheckpoint(
            str(RUN_DIR / "best_model.keras"),
            monitor="val_mae", mode="min", save_best_only=True,
        ),
        keras.callbacks.EarlyStopping(
            monitor="val_mae", patience=PATIENCE, restore_best_weights=True,
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_mae", factor=0.5, patience=8, min_lr=1e-7,
        ),
    ]

    print("\n--- Phase 1: Head fine-tune (backbone frozen) ---")
    model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=EPOCHS_HEAD,
        callbacks=callbacks,
        verbose=2,
    )

    print("\n--- Phase 2: Full fine-tune (last 20% backbone unfrozen) ---")
    mobilenet = model.get_layer("mobilenetv2_0.50_224")
    total_layers = len(mobilenet.layers)
    for i, layer in enumerate(mobilenet.layers):
        layer.trainable = i > total_layers * 0.8

    model.compile(
        optimizer=keras.optimizers.Adam(LEARNING_RATE * 0.1),
        loss=keras.losses.MeanSquaredError(),
        metrics=[keras.metrics.MeanAbsoluteError(name="mae")],
    )

    model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=EPOCHS_HEAD + EPOCHS_FULL,
        initial_epoch=EPOCHS_HEAD,
        callbacks=callbacks,
        verbose=2,
    )

    model.save(str(RUN_DIR / "final_model.keras"))
    val_loss, val_mae = model.evaluate(val_ds, verbose=0)
    print(f"\nVal MAE (norm): {val_mae:.5f}  (pixels): {val_mae * IMAGE_WIDTH:.2f} px")

    # --- Export to TFLite int8 ---
    print("\n--- Exporting int8 TFLite ---")

    def _rep_data():
        for e in train_entries:
            path = str(DATA_DIR / e["image_path"])
            img = tf.io.read_file(path)
            img = tf.image.decode_png(img, channels=3)
            img = tf.image.resize(img, [IMAGE_HEIGHT, IMAGE_WIDTH])
            img = tf.cast(img, tf.float32)
            yield [np.expand_dims(img.numpy(), axis=0)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = _rep_data
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()
    deploy_dir = PROJECT_ROOT / "artifacts" / "deployment" / "center_model_v4_cdcrop_int8"
    os.makedirs(str(deploy_dir), exist_ok=True)
    tflite_path = deploy_dir / "model_int8.tflite"
    with open(str(tflite_path), "wb") as f:
        f.write(tflite_model)
    print(f"Saved: {tflite_path} ({len(tflite_model)} bytes)")

    interpreter = tf.lite.Interpreter(model_path=str(tflite_path), num_threads=1)
    interpreter.allocate_tensors()
    in_det = interpreter.get_input_details()[0]
    out_det = interpreter.get_output_details()[0]

    metadata = {
        "source": str(RUN_DIR / "best_model.keras"),
        "tflite_path": str(tflite_path.relative_to(PROJECT_ROOT)),
        "input_shape": [int(v) for v in in_det["shape"]],
        "output_shape": [int(v) for v in out_det["shape"]],
        "input_scale": float(in_det["quantization"][0]),
        "input_zero_point": int(in_det["quantization"][1]),
        "output_scale": float(out_det["quantization"][0]),
        "output_zero_point": int(out_det["quantization"][1]),
        "val_mae_norm": float(val_mae),
        "val_mae_px": float(val_mae * IMAGE_WIDTH),
        "train_entries": len(train_entries),
        "board_entries": len(board_entries),
        "data_source": "center_training_crops (CD-crop aligned)",
    }
    meta_path = deploy_dir / "metadata.json"
    with open(str(meta_path), "w") as f:
        json.dump(metadata, f, indent=2)
    print(f"Saved: {meta_path}")
    print("Done.")


if __name__ == "__main__":
    main()
