#!/usr/bin/env python3
"""Train the QAT-friendly UNet for gauge center/tip keypoint heatmaps.

Pipeline:
1. Load the ellipse-conditioned 224x224 crops and 56x56 heatmap targets.
2. FP32 training (60 epochs, AdamW + cosine LR).
3. Apply tfmot.quantize_model() for QAT.
4. QAT fine-tune (20 epochs, lower LR).
5. Export int8 TFLite with representative dataset.
6. Activation budget check.
7. Evaluate keypoint error on val/test.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import tensorflow as tf
import tf_keras as keras
import tensorflow_model_optimization as tfmot
from tf_keras import layers
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from embedded_gauge_reading_tinyml.keypoint_unet_224 import build_keypoint_unet_224  # noqa: E402

DATA_DIR = ROOT / "data" / "gauge_keypoint_224"
DEFAULT_OUTPUT = ROOT / "artifacts" / "gauge_keypoint_unet_224g_v1"
HEATMAP_SIZE = 56
SEED = 42


def configure_gpu() -> None:
    gpus = tf.config.list_physical_devices("GPU")
    if gpus:
        tf.config.set_logical_device_configuration(
            gpus[0], [tf.config.LogicalDeviceConfiguration(memory_limit=15000)]
        )


def _load_split(split: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load 224x224 crops + 56x56 center/tip heatmaps.

    The data was pre-generated by prepare_gauge_keypoint_224_data.py.
    Images are named 000000.jpg, 000001.jpg, etc. with matching .npy files.
    """
    img_dir = DATA_DIR / split / "images"
    center_npy = DATA_DIR / split / "center.npy"
    tip_npy = DATA_DIR / split / "tip.npy"
    if not center_npy.exists() or not tip_npy.exists():
        raise FileNotFoundError(f"Missing {center_npy}. Run prepare_gauge_keypoint_224_data.py first.")

    center_hm = np.load(center_npy)
    n = len(center_hm)
    images = np.zeros((n, 224, 224, 1), dtype=np.float32)
    tip_hm = np.load(tip_npy)

    for i in range(n):
        img = np.asarray(Image.open(img_dir / f"{i:06d}.jpg").convert("L"), dtype=np.float32)
        images[i, ..., 0] = img / 255.0

    print(f"  {split}: {n} images loaded, heatmap peaks: c={center_hm.max():.3f}, t={tip_hm.max():.3f}")
    return images, center_hm, tip_hm


@keras.saving.register_keras_serializable()
class WarmupCosineDecay(keras.optimizers.schedules.LearningRateSchedule):
    def __init__(self, peak_lr: float, total_steps: int, warmup_steps: int = 0):
        super().__init__()
        self._peak = peak_lr
        self._total = total_steps
        self._warmup = warmup_steps
        self._cosine = keras.optimizers.schedules.CosineDecay(
            peak_lr, max(1, total_steps - warmup_steps), alpha=0.01,
        )

    def __call__(self, step):
        wf = tf.cast(step, tf.float32) / tf.cast(max(1, self._warmup), tf.float32)
        return tf.where(step < self._warmup, self._peak * wf,
                        self._cosine(step - self._warmup))

    def get_config(self):
        return {"peak_lr": self._peak, "total_steps": self._total, "warmup_steps": self._warmup}


def _focal_heatmap_loss(alpha: float = 2.0, gamma: float = 4.0,
                        center_weight: float = 1.0,
                        tip_weight: float = 1.5) -> callable:
    """Focal loss on per-pixel heatmaps with per-channel weighting.

    center_weight / tip_weight let us bias toward the tip (needle endpoint)
    which is harder to localise because of its finer scale.
    """
    def loss(y_true, y_pred):
        eps = 1e-7
        y_pred = tf.clip_by_value(y_pred, eps, 1.0 - eps)
        # Channel weights: center=1.0, tip=1.5
        channel_w = tf.constant([center_weight, tip_weight], dtype=tf.float32)
        # Focal term: -alpha * (1-p)^gamma * log(p) for foreground, -(1-p)^gamma * log(1-p) for bg
        pos_term = -alpha * tf.pow(1.0 - y_pred, gamma) * tf.math.log(y_pred)
        neg_term = -tf.pow(y_pred, gamma) * tf.math.log(1.0 - y_pred)
        focal = y_true * pos_term + (1.0 - y_true) * neg_term
        # Apply channel weights
        return tf.reduce_mean(focal * channel_w)
    return loss


def _export_int8_tflite(model: keras.Model, sample: np.ndarray,
                         output_path: Path) -> dict:
    def rep():
        rng = np.random.default_rng(SEED)
        for idx in rng.choice(len(sample), size=min(512, len(sample)), replace=False):
            yield [sample[idx:idx+1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = rep
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    blob = converter.convert()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(blob)

    interp = tf.lite.Interpreter(model_content=blob)
    interp.allocate_tensors()
    in_det = interp.get_input_details()[0]
    out_det = interp.get_output_details()[0]
    return {
        "bytes": len(blob),
        "kb": round(len(blob) / 1024, 1),
        "input_shape": in_det["shape"].tolist(),
        "output_shape": out_det["shape"].tolist(),
        "output_scale": out_det["quantization"][0],
        "output_zp": out_det["quantization"][1],
    }


def _decode_heatmap_peak(heatmap: np.ndarray) -> tuple[float, float, float]:
    """Sub-pixel keypoint from heatmap using local softargmax.

    Returns (x_normalized, y_normalized, confidence) in [0, 1].
    """
    h, w = heatmap.shape
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    weights = np.maximum(heatmap - 0.03, 0.0) ** 2
    total = weights.sum()
    if total < 1e-6:
        return 0.5, 0.5, 0.0
    cx = (weights * xx).sum() / total / (w - 1)
    cy = (weights * yy).sum() / total / (h - 1)
    conf = heatmap.max()
    return float(cx), float(cy), float(conf)


def _augment_keypoint_set(
    images: np.ndarray,
    center: np.ndarray,
    tip: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Double the set with flip/rotate/scale-augmented copies.

    why (2026-07-30 lesson): never rotate heatmaps directly — transform the
    image AND the keypoint coordinates, then re-render the heatmaps.  The
    keypoint pipeline had zero augmentation; the ellipse pipeline showed
    flips alone cured a held-out-family failure (test_2 28->6.3px).
    """
    from PIL import Image, ImageEnhance

    rng = np.random.default_rng(SEED)
    aug_images = np.empty_like(images)
    aug_center = np.empty_like(center)
    aug_tip = np.empty_like(tip)
    for i in range(len(images)):
        img = Image.fromarray((images[i, ..., 0] * 255.0).astype(np.uint8))
        gy, gx = np.unravel_index(np.argmax(center[i]), center[i].shape)
        ty, tx = np.unravel_index(np.argmax(tip[i]), tip[i].shape)
        scale = 224 / 56
        cx, cy = gx * scale, gy * scale
        tip_x, tip_y = tx * scale, ty * scale

        if rng.random() < 0.5:
            img = img.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
            cx = 224 - cx
            tip_x = 224 - tip_x

        angle = rng.uniform(-10.0, 10.0)
        if abs(angle) > 0.5:
            img = img.rotate(angle, resample=Image.Resampling.BILINEAR,
                             fillcolor=int(np.mean(images[i]) * 255))
            rad = np.deg2rad(angle)
            c, s = np.cos(rad), np.sin(rad)
            center_px = 112.0
            cx, cy = (center_px + (cx - center_px) * c - (cy - center_px) * s,
                      center_px + (cx - center_px) * s + (cy - center_px) * c)
            tip_x, tip_y = (center_px + (tip_x - center_px) * c - (tip_y - center_px) * s,
                            center_px + (tip_x - center_px) * s + (tip_y - center_px) * c)

        scale_f = rng.uniform(0.9, 1.1)
        if abs(scale_f - 1.0) > 0.01:
            new_size = int(round(224 * scale_f))
            img = img.resize((new_size, new_size), Image.Resampling.BILINEAR)
            canvas = Image.new("L", (224, 224), color=int(np.mean(images[i]) * 255))
            offset = (224 - new_size) // 2
            canvas.paste(img, (offset, offset))
            img = canvas
            cx, cy = cx * scale_f + offset, cy * scale_f + offset
            tip_x, tip_y = tip_x * scale_f + offset, tip_y * scale_f + offset

        img = ImageEnhance.Brightness(img).enhance(float(rng.uniform(0.85, 1.15)))
        aug_images[i, ..., 0] = np.asarray(img, dtype=np.float32) / 255.0
        aug_center[i] = _render_gaussian(cx, cy)
        aug_tip[i] = _render_gaussian(tip_x, tip_y)
    return (
        np.concatenate([images, aug_images], axis=0),
        np.concatenate([center, aug_center], axis=0),
        np.concatenate([tip, aug_tip], axis=0),
    )


def _render_gaussian(x: float, y: float) -> np.ndarray:
    """Render a 56x56 Gaussian heatmap at 224-crop pixel (x, y)."""
    hm_x = x / (224 / 56)
    hm_y = y / (224 / 56)
    yy, xx = np.mgrid[0:56, 0:56].astype(np.float32)
    return np.exp(-((xx - hm_x) ** 2 + (yy - hm_y) ** 2) / (2.0 * 2.0**2)).astype(np.float32)


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--alpha", type=float, default=1.0)
    parser.add_argument("--fp32-epochs", type=int, default=60)
    parser.add_argument("--qat-epochs", type=int, default=20)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--qat-lr", type=float, default=2e-4)
    parser.add_argument("--augment", action="store_true",
                        help="Double the training set with flip/rotate/scale "
                             "augmentation (image + regenerated heatmaps).")
    parser.add_argument("--stride2", action="store_true",
                        help="Use the stride-2 output head (112x112 heatmaps, "
                             "2px cells) — broke the tip <10px wall in screen v6.")
    args = parser.parse_args()

    tf.random.set_seed(SEED); np.random.seed(SEED)
    configure_gpu()
    args.output.mkdir(parents=True, exist_ok=True)

    print("Loading data...")
    train_x, train_c, train_t = _load_split("train")
    val_x, val_c, val_t = _load_split("val")
    if args.augment:
        train_x, train_c, train_t = _augment_keypoint_set(train_x, train_c, train_t)
        print(f"  augmented train: {train_x.shape}")
    # Stack center + tip as 2-channel target
    train_y = np.stack([train_c, train_t], axis=-1)
    val_y = np.stack([val_c, val_t], axis=-1)
    print(f"  train: {train_x.shape}, heatmaps: {train_y.shape}")
    print(f"  val:   {val_x.shape}, heatmaps: {val_y.shape}")

    # Verify heatmaps have valid peaks
    for name, hm in [("train center", train_c), ("train tip", train_t)]:
        peaks = hm.max(axis=(1, 2))
        print(f"  {name}: peak range [{peaks.min():.3f}, {peaks.max():.3f}], mean={peaks.mean():.3f}")

    print(f"\nBuilding keypoint UNet 224 (alpha={args.alpha}, stride2={args.stride2})...")
    model = build_keypoint_unet_224(alpha=args.alpha, stride2=args.stride2)
    model.summary(line_length=100, print_fn=print)
    n_params = int(sum(np.prod(v.shape) for v in model.trainable_variables))
    print(f"Trainable params: {n_params:,} ({n_params / 1e6:.2f}M)")

    if args.stride2:
        # why: the stride-2 head outputs 112x112 heatmaps; upsample the
        # 56x56 GT targets with bilinear so supervision matches the head
        # resolution (symmetric upsampling keeps peaks centered).
        from PIL import Image as PILImage

        def _upsample_hm(hm: np.ndarray) -> np.ndarray:
            out = np.zeros((len(hm), 112, 112), dtype=np.float32)
            for i in range(len(hm)):
                out[i] = np.asarray(
                    PILImage.fromarray(hm[i]).resize((112, 112), PILImage.Resampling.BILINEAR)
                )
            return out

        train_c, train_t = _upsample_hm(train_c), _upsample_hm(train_t)
        val_c, val_t = _upsample_hm(val_c), _upsample_hm(val_t)
        print("  upsampled heatmaps to 112x112 for stride-2 head")
    train_y = np.stack([train_c, train_t], axis=-1)
    val_y = np.stack([val_c, val_t], axis=-1)

    loss = _focal_heatmap_loss(alpha=2.0, gamma=4.0, center_weight=1.0, tip_weight=8.0)
    steps_per_epoch = max(1, len(train_x) // args.batch_size)

    # FP32 training
    lr = WarmupCosineDecay(args.lr, steps_per_epoch * args.fp32_epochs, steps_per_epoch * 3)
    model.compile(optimizer=keras.optimizers.AdamW(lr, weight_decay=1e-4), loss=loss)
    print(f"\nFP32 training ({args.fp32_epochs} epochs)...")
    model.fit(
        train_x, train_y, batch_size=args.batch_size, epochs=args.fp32_epochs,
        validation_data=(val_x, val_y),
        callbacks=[keras.callbacks.ReduceLROnPlateau(
            factor=0.5, patience=5, min_lr=1e-6, verbose=1,
        )],
        verbose=2,
    )
    model.save(args.output / "model_fp32.keras")

    # Quick eval of fp32 model on val
    print("\nFP32 keypoint accuracy on val (first 100 images):")
    val_sample = val_x[:100]
    preds = model.predict(val_sample, batch_size=8, verbose=0)
    center_err_px, tip_err_px = [], []
    for i in range(100):
        pcx, pcy, pc_conf = _decode_heatmap_peak(preds[i, ..., 0])
        tcx, tcy, tc_conf = _decode_heatmap_peak(preds[i, ..., 1])
        # GT in heatmap space to normalized
        gcx, gcy, gc_conf = _decode_heatmap_peak(val_c[i])
        gtx, gty, gt_conf = _decode_heatmap_peak(val_t[i])
        center_err_px.append(np.sqrt((pcx - gcx)**2 + (pcy - gcy)**2) * 224)
        tip_err_px.append(np.sqrt((tcx - gtx)**2 + (tcy - gty)**2) * 224)
    center_err_px = np.array(center_err_px)
    tip_err_px = np.array(tip_err_px)
    print(f"  Center MAE: {center_err_px.mean():.2f} px (median {np.median(center_err_px):.2f})")
    print(f"  Tip MAE:    {tip_err_px.mean():.2f} px (median {np.median(tip_err_px):.2f})")
    print(f"  Center % ≤4/8px: {(center_err_px<=4).mean()*100:.1f}% / {(center_err_px<=8).mean()*100:.1f}%")
    print(f"  Tip % ≤4/8px:    {(tip_err_px<=4).mean()*100:.1f}% / {(tip_err_px<=8).mean()*100:.1f}%")

    # QAT
    print("\nApplying QAT...")
    qat_model = tfmot.quantization.keras.quantize_model(model)
    qat_output_name = qat_model.outputs[0].name.split("/")[0]
    qat_lr = WarmupCosineDecay(args.qat_lr, steps_per_epoch * args.qat_epochs, steps_per_epoch)
    qat_model.compile(
        optimizer=keras.optimizers.AdamW(qat_lr, weight_decay=1e-5),
        loss={qat_output_name: loss},
    )
    print(f"QAT training ({args.qat_epochs} epochs)...")
    qat_model.fit(
        train_x, {qat_output_name: train_y}, batch_size=args.batch_size,
        epochs=args.qat_epochs,
        validation_data=(val_x, {qat_output_name: val_y}),
        verbose=2,
    )
    qat_model.save(args.output / "model_qat.keras")

    # Export int8 TFLite via PTQ on the fp32 model (not QAT).
    # Why PTQ not QAT: the UNet's Concatenate layers between decoder and skip
    # connections have different int8 quantization scales after tfmot wrapping,
    # which violates TFLite's "same scale constraint" for concatenation.
    # PTQ handles this internally by inserting requantization nodes.
    # Also: the UpSampling2D with bilinear interpolation is supported by
    # TFLite (unlike bicubic), so the model converts cleanly.
    print("\nExporting int8 TFLite (PTQ on fp32 model)...")
    contract = _export_int8_tflite(model, train_x, args.output / "model_int8.tflite")
    print(f"  Size: {contract['kb']} KB ({contract['bytes'] / 1e6:.2f} MB)")
    print(f"  Input: {contract['input_shape']}")
    print(f"  Output: {contract['output_shape']}")

    # Quick int8 eval
    print("\nInt8 keypoint accuracy on val (first 100 images):")
    interp = tf.lite.Interpreter(model_path=str(args.output / "model_int8.tflite"))
    interp.allocate_tensors()
    in_det = interp.get_input_details()[0]
    out_det = interp.get_output_details()[0]
    in_scale, in_zp = in_det["quantization"]
    out_scale, out_zp = out_det["quantization"]
    center_err_px_i, tip_err_px_i = [], []
    for i in range(100):
        xq = np.clip(np.round(val_sample[i:i+1] / in_scale + in_zp), -128, 127).astype(np.int8)
        interp.set_tensor(in_det["index"], xq)
        interp.invoke()
        raw = interp.get_tensor(out_det["index"])
        hm = ((raw.astype(np.float32) - out_zp) * out_scale)[0]
        pcx, pcy, _ = _decode_heatmap_peak(hm[..., 0])
        tcx, tcy, _ = _decode_heatmap_peak(hm[..., 1])
        gcx, gcy, _ = _decode_heatmap_peak(val_c[i])
        gtx, gty, _ = _decode_heatmap_peak(val_t[i])
        center_err_px_i.append(np.sqrt((pcx - gcx)**2 + (pcy - gcy)**2) * 224)
        tip_err_px_i.append(np.sqrt((tcx - gtx)**2 + (tcy - gty)**2) * 224)
    center_err_px_i = np.array(center_err_px_i)
    tip_err_px_i = np.array(tip_err_px_i)
    print(f"  Center MAE: {center_err_px_i.mean():.2f} px (median {np.median(center_err_px_i):.2f})")
    print(f"  Tip MAE:    {tip_err_px_i.mean():.2f} px (median {np.median(tip_err_px_i):.2f})")
    print(f"  Center % ≤4/8px: {(center_err_px_i<=4).mean()*100:.1f}% / {(center_err_px_i<=8).mean()*100:.1f}%")
    print(f"  Tip % ≤4/8px:    {(tip_err_px_i<=4).mean()*100:.1f}% / {(tip_err_px_i<=8).mean()*100:.1f}%")

    # Report
    report = {
        "model": f"keypoint_unet_224_a{args.alpha}",
        "input_shape": [224, 224, 1],
        "output_shape": [HEATMAP_SIZE, HEATMAP_SIZE, 2],
        "alpha": args.alpha,
        "n_params": n_params,
        "int8_size_kb": contract["kb"],
        "fp32_center_mae_px": float(center_err_px.mean()),
        "fp32_tip_mae_px": float(tip_err_px.mean()),
        "int8_center_mae_px": float(center_err_px_i.mean()),
        "int8_tip_mae_px": float(tip_err_px_i.mean()),
    }
    (args.output / "report.json").write_text(json.dumps(report, indent=2))
    print(f"\nReport saved to {args.output / 'report.json'}")


if __name__ == "__main__":
    sys.exit(main())
