#!/usr/bin/env python3
"""Train the board-crop SimCC keypoint stage from OBB outputs.

This wrapper keeps the next-stage job discoverable while reusing the shared
center/tip SimCC KD+QAT implementation. By default it trains on the reviewed
board-capture manifest and consumes the crop boxes generated by the deployed
OBB model, so the learned keypoints match the actual first-stage deployment
contract.
"""

from __future__ import annotations

import sys
from pathlib import Path


PROJECT_ROOT: Path = Path(__file__).resolve().parents[1]
REPO_ROOT: Path = PROJECT_ROOT.parent
DEFAULT_MANIFEST: Path = REPO_ROOT / "tmp" / "labelled_captured_images_board_bbox_plus_center_tip_v3.json"
FALLBACK_MANIFEST: Path = REPO_ROOT / "tmp" / "labelled_captured_images_board_bbox_plus_board_reviews.json"
DEFAULT_FALLBACK_MANIFEST: Path = PROJECT_ROOT / "data" / "labelled_captured_images.json"
DEFAULT_OBB_CROP_MANIFEST: Path = REPO_ROOT / "tmp" / "obb_output" / "obb_crop_manifest.json"
DEFAULT_TEACHER_MODEL: Path = (
    PROJECT_ROOT
    / "artifacts"
    / "training"
    / "center_simcc_kd_qat_20260620_short"
    / "center_simcc_float.keras"
)
DEFAULT_OUTPUT_DIR: Path = PROJECT_ROOT / "artifacts" / "training" / "obb_board_simcc_kd_qat"
DEFAULT_TIP_LOSS_WEIGHT: float = 2.0


def _inject_default_args(argv: list[str]) -> list[str]:
    """Prepend board-specific defaults when the caller did not provide them."""

    pairs: list[tuple[str, str]] = []
    if DEFAULT_MANIFEST.exists():
        manifest = DEFAULT_MANIFEST
    elif FALLBACK_MANIFEST.exists():
        manifest = FALLBACK_MANIFEST
    else:
        manifest = DEFAULT_FALLBACK_MANIFEST
    pairs.extend(
        [
            ("--manifest", manifest.as_posix()),
            ("--obb-crop-manifest", DEFAULT_OBB_CROP_MANIFEST.as_posix()),
            ("--output-dir", DEFAULT_OUTPUT_DIR.as_posix()),
            ("--tip-loss-weight", f"{DEFAULT_TIP_LOSS_WEIGHT:g}"),
        ]
    )
    if DEFAULT_TEACHER_MODEL.exists():
        pairs.extend(
            [
                ("--teacher-model-path", DEFAULT_TEACHER_MODEL.as_posix()),
            ]
        )

    def _has_option(option: str) -> bool:
        return any(arg == option or arg.startswith(f"{option}=") for arg in argv)

    injected: list[str] = []
    for option, value in pairs:
        if not _has_option(option):
            injected.extend([option, value])
    return injected + argv


def main() -> None:
    """Run the shared SimCC trainer with board-specific defaults."""

    from train_qat_obb_simcc_combined import main as train_main

    sys.argv = [sys.argv[0], *_inject_default_args(sys.argv[1:])]
    train_main()


if __name__ == "__main__":
	main()
