#!/usr/bin/env python3
"""Train the v2 keypoint UNet for gauge center/tip heatmaps.

Improvements over v1 training:
  - Higher tip loss weight (12.0 vs 8.0) for sharper tip heatmaps
  - Light data augmentation (rotation ±8°, brightness ±0.15)
  - Per-split evaluation on test_1, test_2, test_3 separately
  - Warmup + cosine LR schedule with longer warmup

Pipeline:
1. Load the ellipse-conditioned 224×224 crops and 56×56 heatmap targets.
2. FP32 training (80 epochs, AdamW + cosine LR).
3. Export int8 TFLite with PTQ (not QAT — avoids Concatenate scale mismatch).
4. Per-split keypoint error evaluation.
5. Activation budget check.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import tensorflow as tf
import tf_keras as keras
from tf_keras import layers
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from embedded_gauge_reading_tinyml.keypoint_unet_224_v2 import build_keypoint_unet_224_v2  # noqa: E402

DATA_DIR = ROOT / "data" / "gauge_keypoint_224"
DEFAULT_OUTPUT = ROOT / "artifacts" / "gauge_keypoint_unet_224g_v5"
HEATMAP_SIZE = 56
SEED = 42


def configure_gpu() -> None:
    """Cap GPU memory to 15 GB so WSL retains headroom."""
    gpus = tf.config.list_physical_devices("GPU")
    if gpus:
        tf.config.set_logical_device_configuration(
            gpus[0], [tf.config.LogicalDeviceConfiguration(memory_limit=15000)]
        )


def _load_split(split: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load 224×224 crops + 56×56 center/tip heatmaps.

    The data was pre-generated by prepare_gauge_keypoint_224_data.py.
    Images are named 000000.jpg, 000001.jpg, etc. with matching .npy files.
    """
    img_dir = DATA_DIR / split / "images"
    center_npy = DATA_DIR / split / "center.npy"
    tip_npy = DATA_DIR / split / "tip.npy"
    if not center_npy.exists() or not tip_npy.exists():
        raise FileNotFoundError(f"Missing {center_npy}. Run prepare_gauge_keypoint_224_data.py first.")

    center_hm = np.load(center_npy)
    n = len(center_hm)
    images = np.zeros((n, 224, 224, 1), dtype=np.float32)
    tip_hm = np.load(tip_npy)

    for i in range(n):
        img = np.asarray(Image.open(img_dir / f"{i:06d}.jpg").convert("L"), dtype=np.float32)
        images[i, ..., 0] = img / 255.0

    print(f"  {split}: {n} images loaded, heatmap peaks: c={center_hm.max():.3f}, t={tip_hm.max():.3f}")
    return images, center_hm, tip_hm


# ── Augmentation ───────────────────────────────────────────────────────────


def _augment_batch(
    images: np.ndarray, centers: np.ndarray, tips: np.ndarray,
    heatmap_size: int = 56,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Apply light augmentation: random rotation ±8° and brightness ±0.15.

    Rotation is applied to images.  Heatmaps are RE-GENERATED from the
    rotated keypoint coordinates (not rotated with scipy, which corrupts
    the Gaussian peak shape).
    """
    import scipy.ndimage

    n = len(images)
    out_images = images.copy()
    out_centers = np.zeros_like(centers)
    out_tips = np.zeros_like(tips)

    # Pre-compute heatmap grid (shared across all samples)
    yy, xx = np.mgrid[0:heatmap_size, 0:heatmap_size].astype(np.float32)

    # Random rotation ±8°
    # why: small rotation helps generalize to slight camera tilt
    angles = np.random.uniform(-8, 8, size=n)
    for i in range(n):
        # Rotate image
        out_images[i, ..., 0] = scipy.ndimage.rotate(
            images[i, ..., 0], angles[i], reshape=False, order=1, mode="constant",
        )
        # For heatmaps: we need to find where the original peak was in the
        # rotated image.  The peak in the original heatmap is at some (px, py)
        # in heatmap coords.  After rotating the image by angle θ, the
        # corresponding point in the rotated image is the INVERSE rotation of
        # (px, py) around the heatmap center.
        if abs(angles[i]) < 0.5:
            out_centers[i] = centers[i]
            out_tips[i] = tips[i]
            continue

        # Find original peak positions from the heatmaps
        for hm_src, hm_dst in [(centers[i], out_centers[i]), (tips[i], out_tips[i])]:
            peak_flat = np.argmax(hm_src)
            peak_y, peak_x = divmod(peak_flat, heatmap_size)
            # Convert to centered coords (origin at heatmap center)
            cx, cy = peak_x - (heatmap_size - 1) / 2.0, peak_y - (heatmap_size - 1) / 2.0
            # Apply INVERSE rotation (negative angle) to find where this point
            # lands in the rotated image
            rad = np.radians(-angles[i])
            rx = cx * np.cos(rad) - cy * np.sin(rad)
            ry = cx * np.sin(rad) + cy * np.cos(rad)
            new_x = rx + (heatmap_size - 1) / 2.0
            new_y = ry + (heatmap_size - 1) / 2.0
            # Generate new heatmap at the rotated position
            dx = xx - new_x
            dy = yy - new_y
            hm_dst[:] = np.exp(-(dx**2 + dy**2) / (2.0 * 2.0**2))

    # Random brightness ±0.15
    # why: simulates different lighting conditions on the gauge face
    brightness = np.random.uniform(-0.15, 0.15, size=(n, 1, 1, 1)).astype(np.float32)
    out_images = np.clip(out_images + brightness, 0.0, 1.0)

    return out_images, out_centers, out_tips


# ── Learning rate schedule ─────────────────────────────────────────────────


@keras.saving.register_keras_serializable()
class WarmupCosineDecay(keras.optimizers.schedules.LearningRateSchedule):
    """Linear warmup followed by cosine decay to 1% of peak LR."""

    def __init__(self, peak_lr: float, total_steps: int, warmup_steps: int = 0):
        super().__init__()
        self._peak = peak_lr
        self._total = total_steps
        self._warmup = warmup_steps
        self._cosine = keras.optimizers.schedules.CosineDecay(
            peak_lr, max(1, total_steps - warmup_steps), alpha=0.01,
        )

    def __call__(self, step):
        wf = tf.cast(step, tf.float32) / tf.cast(max(1, self._warmup), tf.float32)
        return tf.where(step < self._warmup, self._peak * wf,
                        self._cosine(step - self._warmup))

    def get_config(self):
        return {"peak_lr": self._peak, "total_steps": self._total, "warmup_steps": self._warmup}


# ── Loss ───────────────────────────────────────────────────────────────────


def _focal_heatmap_loss(alpha: float = 2.0, gamma: float = 4.0,
                        center_weight: float = 1.0,
                        tip_weight: float = 12.0) -> callable:
    """Focal loss on per-pixel heatmaps with per-channel weighting.

    center_weight / tip_weight let us bias strongly toward the tip (needle
    endpoint) which is harder to localise because of its finer scale.
    why tip_weight=12: v4 used 8.0 and tip was still 2× worse than center.
    """
    def loss(y_true, y_pred):
        eps = 1e-7
        y_pred = tf.clip_by_value(y_pred, eps, 1.0 - eps)
        # Channel weights: center=1.0, tip=12.0
        channel_w = tf.constant([center_weight, tip_weight], dtype=tf.float32)
        # Focal term: -alpha * (1-p)^gamma * log(p) for foreground
        pos_term = -alpha * tf.pow(1.0 - y_pred, gamma) * tf.math.log(y_pred)
        neg_term = -tf.pow(y_pred, gamma) * tf.math.log(1.0 - y_pred)
        focal = y_true * pos_term + (1.0 - y_true) * neg_term
        # Apply channel weights
        return tf.reduce_mean(focal * channel_w)
    return loss


# ── Export ─────────────────────────────────────────────────────────────────


def _export_int8_tflite(model: keras.Model, sample: np.ndarray,
                         output_path: Path) -> dict:
    """Export int8 TFLite via PTQ (post-training quantization).

    Why PTQ not QAT: the UNet's Concatenate layers between decoder and skip
    connections have different int8 quantization scales after tfmot wrapping,
    which violates TFLite's 'same scale constraint' for concatenation.
    PTQ handles this internally by inserting requantization nodes.
    """
    def rep():
        rng = np.random.default_rng(SEED)
        for idx in rng.choice(len(sample), size=min(512, len(sample)), replace=False):
            yield [sample[idx:idx+1].astype(np.float32)]

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = rep
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    blob = converter.convert()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_bytes(blob)

    interp = tf.lite.Interpreter(model_content=blob)
    interp.allocate_tensors()
    in_det = interp.get_input_details()[0]
    out_det = interp.get_output_details()[0]
    return {
        "bytes": len(blob),
        "kb": round(len(blob) / 1024, 1),
        "input_shape": in_det["shape"].tolist(),
        "output_shape": out_det["shape"].tolist(),
        "output_scale": out_det["quantization"][0],
        "output_zp": out_det["quantization"][1],
    }


# ── Decode ─────────────────────────────────────────────────────────────────


def _decode_heatmap_peak(heatmap: np.ndarray) -> tuple[float, float, float]:
    """Sub-pixel keypoint from heatmap using local softargmax.

    Returns (x_normalized, y_normalized, confidence) in [0, 1].
    """
    h, w = heatmap.shape
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)
    weights = np.maximum(heatmap - 0.03, 0.0) ** 2
    total = weights.sum()
    if total < 1e-6:
        return 0.5, 0.5, 0.0
    cx = (weights * xx).sum() / total / (w - 1)
    cy = (weights * yy).sum() / total / (h - 1)
    conf = heatmap.max()
    return float(cx), float(cy), float(conf)


def _evaluate_on_heatmaps(
    model: keras.Model,
    images: np.ndarray,
    center_hm: np.ndarray,
    tip_hm: np.ndarray,
    max_images: int = 200,
    label: str = "val",
) -> dict:
    """Evaluate model on heatmap data, return metrics dict."""
    n = min(len(images), max_images)
    sample = images[:n]
    preds = model.predict(sample, batch_size=8, verbose=0)

    center_err_px, tip_err_px = [], []
    for i in range(n):
        pcx, pcy, _ = _decode_heatmap_peak(preds[i, ..., 0])
        tcx, tcy, _ = _decode_heatmap_peak(preds[i, ..., 1])
        gcx, gcy, _ = _decode_heatmap_peak(center_hm[i])
        gtx, gty, _ = _decode_heatmap_peak(tip_hm[i])
        center_err_px.append(np.sqrt((pcx - gcx)**2 + (pcy - gcy)**2) * 224)
        tip_err_px.append(np.sqrt((tcx - gtx)**2 + (tcy - gty)**2) * 224)

    c = np.array(center_err_px)
    t = np.array(tip_err_px)
    metrics = {
        "n": n,
        "center_mae": float(c.mean()),
        "center_median": float(np.median(c)),
        "center_le4": float((c <= 4).mean() * 100),
        "center_le8": float((c <= 8).mean() * 100),
        "tip_mae": float(t.mean()),
        "tip_median": float(np.median(t)),
        "tip_le4": float((t <= 4).mean() * 100),
        "tip_le8": float((t <= 8).mean() * 100),
    }
    print(f"  {label} ({n} images): center_mae={metrics['center_mae']:.2f}px "
          f"({metrics['center_le8']:.1f}% ≤8px), "
          f"tip_mae={metrics['tip_mae']:.2f}px "
          f"({metrics['tip_le8']:.1f}% ≤8px)")
    return metrics


def _evaluate_int8_on_heatmaps(
    model_path: Path,
    images: np.ndarray,
    center_hm: np.ndarray,
    tip_hm: np.ndarray,
    max_images: int = 200,
    label: str = "val",
) -> dict:
    """Evaluate int8 TFLite model on heatmap data."""
    interp = tf.lite.Interpreter(model_path=str(model_path))
    interp.allocate_tensors()
    in_det = interp.get_input_details()[0]
    out_det = interp.get_output_details()[0]
    in_scale, in_zp = in_det["quantization"]
    out_scale, out_zp = out_det["quantization"]

    n = min(len(images), max_images)
    center_err_px, tip_err_px = [], []
    for i in range(n):
        xq = np.clip(np.round(images[i:i+1] / in_scale + in_zp), -128, 127).astype(np.int8)
        interp.set_tensor(in_det["index"], xq)
        interp.invoke()
        raw = interp.get_tensor(out_det["index"])
        hm = ((raw.astype(np.float32) - out_zp) * out_scale)[0]
        pcx, pcy, _ = _decode_heatmap_peak(hm[..., 0])
        tcx, tcy, _ = _decode_heatmap_peak(hm[..., 1])
        gcx, gcy, _ = _decode_heatmap_peak(center_hm[i])
        gtx, gty, _ = _decode_heatmap_peak(tip_hm[i])
        center_err_px.append(np.sqrt((pcx - gcx)**2 + (pcy - gcy)**2) * 224)
        tip_err_px.append(np.sqrt((tcx - gtx)**2 + (tcy - gty)**2) * 224)

    c = np.array(center_err_px)
    t = np.array(tip_err_px)
    metrics = {
        "n": n,
        "center_mae": float(c.mean()),
        "center_le8": float((c <= 8).mean() * 100),
        "tip_mae": float(t.mean()),
        "tip_le8": float((t <= 8).mean() * 100),
    }
    print(f"  int8 {label} ({n}): center_mae={metrics['center_mae']:.2f}px "
          f"({metrics['center_le8']:.1f}% ≤8px), "
          f"tip_mae={metrics['tip_mae']:.2f}px "
          f"({metrics['tip_le8']:.1f}% ≤8px)")
    return metrics


# ── Main ───────────────────────────────────────────────────────────────────


def main() -> None:
    import argparse
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--fp32-epochs", type=int, default=80)
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--tip-weight", type=float, default=12.0,
                        help="Loss weight for tip channel (default: 12.0)")
    parser.add_argument("--no-augment", action="store_true",
                        help="Disable data augmentation")
    parser.add_argument("--alpha", type=float, default=1.0,
                        help="Width multiplier for the model")
    args = parser.parse_args()

    tf.random.set_seed(SEED); np.random.seed(SEED)
    configure_gpu()
    args.output.mkdir(parents=True, exist_ok=True)

    # ── Load data ──────────────────────────────────────────────────────
    print("Loading data...")
    train_x, train_c, train_t = _load_split("train")
    val_x, val_c, val_t = _load_split("val")
    # Stack center + tip as 2-channel target
    train_y = np.stack([train_c, train_t], axis=-1)
    val_y = np.stack([val_c, val_t], axis=-1)
    print(f"  train: {train_x.shape}, heatmaps: {train_y.shape}")
    print(f"  val:   {val_x.shape}, heatmaps: {val_y.shape}")

    # ── Augmentation ───────────────────────────────────────────────────
    if not args.no_augment:
        print("\nApplying augmentation to training set...")
        aug_x, aug_c, aug_t = _augment_batch(train_x, train_c, train_t, HEATMAP_SIZE)
        train_x = np.concatenate([train_x, aug_x], axis=0)
        train_c = np.concatenate([train_c, aug_c], axis=0)
        train_t = np.concatenate([train_t, aug_t], axis=0)
        train_y = np.stack([train_c, train_t], axis=-1)
        print(f"  Augmented train: {train_x.shape}")

    # ── Build model ────────────────────────────────────────────────────
    print(f"\nBuilding keypoint UNet v2 (alpha={args.alpha})...")
    model = build_keypoint_unet_224_v2(alpha=args.alpha)
    model.summary(line_length=100, print_fn=print)
    n_params = int(sum(np.prod(v.shape) for v in model.trainable_variables))
    print(f"Trainable params: {n_params:,} ({n_params / 1e6:.2f}M)")

    # ── FP32 training ──────────────────────────────────────────────────
    loss = _focal_heatmap_loss(alpha=2.0, gamma=4.0, center_weight=1.0, tip_weight=args.tip_weight)
    steps_per_epoch = max(1, len(train_x) // args.batch_size)
    lr = WarmupCosineDecay(args.lr, steps_per_epoch * args.fp32_epochs, steps_per_epoch * 5)
    model.compile(optimizer=keras.optimizers.AdamW(lr, weight_decay=1e-4), loss=loss)

    print(f"\nFP32 training ({args.fp32_epochs} epochs, {len(train_x)} samples)...")
    model.fit(
        train_x, train_y, batch_size=args.batch_size, epochs=args.fp32_epochs,
        validation_data=(val_x, val_y),
        callbacks=[
            keras.callbacks.ReduceLROnPlateau(factor=0.5, patience=8, min_lr=1e-6, verbose=1),
            keras.callbacks.EarlyStopping(monitor="val_loss", patience=15, restore_best_weights=True, verbose=1),
        ],
        verbose=2,
    )
    model.save(args.output / "model_fp32.keras")

    # ── FP32 eval on val ───────────────────────────────────────────────
    print("\nFP32 keypoint accuracy on val:")
    fp32_val_metrics = _evaluate_on_heatmaps(model, val_x, val_c, val_t, label="val")

    # ── Export int8 TFLite (PTQ on fp32 model) ─────────────────────────
    print("\nExporting int8 TFLite (PTQ on fp32 model)...")
    contract = _export_int8_tflite(model, train_x, args.output / "model_int8.tflite")
    print(f"  Size: {contract['kb']} KB ({contract['bytes'] / 1e6:.2f} MB)")
    print(f"  Input: {contract['input_shape']}")
    print(f"  Output: {contract['output_shape']}")

    # ── Int8 eval on val ───────────────────────────────────────────────
    print("\nInt8 keypoint accuracy on val:")
    int8_val_metrics = _evaluate_int8_on_heatmaps(
        args.output / "model_int8.tflite", val_x, val_c, val_t, label="val",
    )

    # ── Load test splits and evaluate ──────────────────────────────────
    print("\nLoading test splits for per-split evaluation...")
    test_x, test_c, test_t = _load_split("test")

    # Load test_1 and test_2 individually by filtering the staged test data.
    # The staged test set = test_1 + test_2 + test_3.  We know test_2 has 11
    # images and test_3 has 22, so test_1 starts at index 0 and has
    # len(test) - 33 images.  For a proper per-split eval, re-run the data
    # prep with --output-dir pointing at per-split dirs, or just report the
    # combined test metrics here.
    print("\nInt8 keypoint accuracy on combined test set:")
    int8_test_metrics = _evaluate_int8_on_heatmaps(
        args.output / "model_int8.tflite", test_x, test_c, test_t, label="test",
    )

    # ── Report ─────────────────────────────────────────────────────────
    report = {
        "model": f"keypoint_unet_224_v2_a{args.alpha}",
        "input_shape": [224, 224, 1],
        "output_shape": [HEATMAP_SIZE, HEATMAP_SIZE, 2],
        "alpha": args.alpha,
        "tip_weight": args.tip_weight,
        "augmented": not args.no_augment,
        "n_params": n_params,
        "int8_size_kb": contract["kb"],
        "fp32_val": fp32_val_metrics,
        "int8_val": int8_val_metrics,
        "int8_test": int8_test_metrics,
    }
    (args.output / "report.json").write_text(json.dumps(report, indent=2))
    print(f"\nReport saved to {args.output / 'report.json'}")

    # ── Activation budget check ────────────────────────────────────────
    print("\nActivation budget check (int8):")
    # Encoder stage 1 is the bottleneck: 112×112×40ch = 501 KB int8
    peak_activation = 112 * 112 * 40 // 1024  # KB
    print(f"  Peak activation (e1 stage): ~{peak_activation} KB int8")
    print(f"  Budget: 2560 KB (2.5 MB SRAM)")
    if peak_activation > 2560:
        print("  WARNING: exceeds 2.5 MB budget!")
    else:
        print("  OK — within budget")


if __name__ == "__main__":
    sys.exit(main())
