"""Export utilities for turning the calibrated scalar CNN into board artifacts."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
from typing import Any, Iterable

import keras
import numpy as np
import tensorflow as tf

from embedded_gauge_reading_tinyml.dataset import load_dataset
from embedded_gauge_reading_tinyml.gauge.processing import load_gauge_specs
from embedded_gauge_reading_tinyml.presets import (
    DEFAULT_CROP_PAD_RATIO,
    DEFAULT_GAUGE_ID,
    DEFAULT_IMAGE_HEIGHT,
    DEFAULT_IMAGE_WIDTH,
)
from embedded_gauge_reading_tinyml.training import (
    LABELLED_DIR,
    RAW_DIR,
    TrainingExample,
    TrainConfig,
    _build_training_examples,
    _load_hard_case_examples,
    _split_examples,
)


@dataclass(frozen=True)
class ExportConfig:
    """Settings for the board export pipeline."""

    model_path: Path
    output_dir: Path
    hard_case_manifest: Path
    representative_count: int = 32
    image_height: int = DEFAULT_IMAGE_HEIGHT
    image_width: int = DEFAULT_IMAGE_WIDTH
    gauge_id: str = DEFAULT_GAUGE_ID
    crop_pad_ratio: float = DEFAULT_CROP_PAD_RATIO
    legacy_mobilenetv2_preprocess: bool = True


@dataclass(frozen=True)
class ExportResult:
    """Files and quantization details generated by export."""

    source_model_path: Path
    tflite_path: Path
    metadata_path: Path
    input_shape: tuple[int, ...]
    output_shape: tuple[int, ...]
    input_scale: float
    input_zero_point: int
    output_scale: float
    output_zero_point: int
    representative_examples: int


def _resolve_repo_path(path: Path, repo_root: Path) -> Path:
    """Resolve a relative repo path against the repository root."""
    if path.is_absolute():
        return path
    return repo_root / path


def _load_model(model_path: Path, *, legacy_mobilenetv2_preprocess: bool) -> keras.Model:
    """Load the calibrated scalar model artifact."""
    custom_objects: dict[str, Any] = {
        "preprocess_input": tf.keras.applications.mobilenet_v2.preprocess_input
    }
    if legacy_mobilenetv2_preprocess:
        print("[EXPORT] Legacy MobileNetV2 preprocess support enabled.", flush=True)
    model = keras.models.load_model(model_path, custom_objects=custom_objects)
    print(f"[EXPORT] Loaded model '{model.name}' from {model_path}.", flush=True)
    return model


def _build_representative_examples(
    *,
    hard_case_manifest: Path,
    image_height: int,
    image_width: int,
    representative_count: int,
) -> list[TrainingExample]:
    """Collect a deterministic slice of labeled images for TFLite calibration."""
    config = TrainConfig(
        image_height=image_height,
        image_width=image_width,
        crop_pad_ratio=DEFAULT_CROP_PAD_RATIO,
        augment_training=False,
        hard_case_manifest=None,
        hard_case_repeat=0,
    )

    specs = load_gauge_specs()
    spec = specs[config.gauge_id]

    print("[EXPORT] Loading labelled dataset for representative examples...", flush=True)
    samples = load_dataset(labelled_dir=LABELLED_DIR, raw_dir=RAW_DIR)
    examples, dropped_out_of_sweep = _build_training_examples(
        samples,
        spec,
        strict_labels=config.strict_labels,
        crop_pad_ratio=config.crop_pad_ratio,
    )
    split = _split_examples(examples, config)

    rep_train_examples: list[TrainingExample] = split.train_examples[:representative_count]
    hard_case_examples: list[TrainingExample] = _load_hard_case_examples(
        hard_case_manifest,
        image_height=image_height,
        image_width=image_width,
    )

    print(
        "[EXPORT] Representative data: "
        f"train={len(rep_train_examples)} "
        f"hard_cases={len(hard_case_examples)} "
        f"dropped_out_of_sweep={dropped_out_of_sweep}",
        flush=True,
    )
    return hard_case_examples + rep_train_examples


def _representative_dataset(
    examples: Iterable[TrainingExample],
    *,
    image_height: int,
    image_width: int,
) -> Iterable[list[np.ndarray]]:
    """Yield calibration images in the format TensorFlow Lite expects."""
    for example in examples:
        image_path = Path(example.image_path)
        image = tf.keras.utils.load_img(
            image_path,
            target_size=(image_height, image_width),
        )
        image_array = tf.keras.utils.img_to_array(image).astype(np.float32) / 255.0
        yield [np.expand_dims(image_array, axis=0)]


def _inspect_tflite_io(
    tflite_path: Path,
) -> tuple[tuple[int, ...], tuple[int, ...], float, int, float, int]:
    """Inspect the quantized input/output tensors of a TFLite model."""
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path), num_threads=1)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    input_shape = tuple(int(value) for value in input_details["shape"])
    output_shape = tuple(int(value) for value in output_details["shape"])
    input_scale = float(input_details["quantization"][0])
    input_zero_point = int(input_details["quantization"][1])
    output_scale = float(output_details["quantization"][0])
    output_zero_point = int(output_details["quantization"][1])
    return (
        input_shape,
        output_shape,
        input_scale,
        input_zero_point,
        output_scale,
        output_zero_point,
    )


def build_export_metadata(
    *,
    source_model_path: Path,
    tflite_path: Path,
    input_shape: tuple[int, ...],
    output_shape: tuple[int, ...],
    input_scale: float,
    input_zero_point: int,
    output_scale: float,
    output_zero_point: int,
    representative_examples: int,
    hard_case_manifest: Path,
) -> dict[str, Any]:
    """Build a serializable metadata payload for firmware handoff."""
    return {
        "source_model_path": str(source_model_path),
        "tflite_path": str(tflite_path),
        "input_shape": list(input_shape),
        "output_shape": list(output_shape),
        "input_scale": input_scale,
        "input_zero_point": input_zero_point,
        "output_scale": output_scale,
        "output_zero_point": output_zero_point,
        "representative_examples": representative_examples,
        "hard_case_manifest": str(hard_case_manifest),
        "board_input_size": {
            "height": int(input_shape[1]) if len(input_shape) > 1 else None,
            "width": int(input_shape[2]) if len(input_shape) > 2 else None,
        },
        "board_notes": (
            "Use this artifact with the STM32 capture path that already crops to "
            "224x224 and preserves gauge geometry."
        ),
    }


def export_board_tflite_artifacts(config: ExportConfig) -> ExportResult:
    """Export the calibrated scalar CNN into an int8 TFLite bundle."""
    config.output_dir.mkdir(parents=True, exist_ok=True)

    model = _load_model(
        config.model_path,
        legacy_mobilenetv2_preprocess=config.legacy_mobilenetv2_preprocess,
    )
    representative_examples = _build_representative_examples(
        hard_case_manifest=config.hard_case_manifest,
        image_height=config.image_height,
        image_width=config.image_width,
        representative_count=config.representative_count,
    )

    print("[EXPORT] Converting model to fully quantized int8 TFLite...", flush=True)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: _representative_dataset(
        representative_examples,
        image_height=config.image_height,
        image_width=config.image_width,
    )
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflite_model: bytes = converter.convert()

    tflite_path = config.output_dir / "model_int8.tflite"
    tflite_path.write_bytes(tflite_model)
    print(f"[EXPORT] Wrote TFLite model to {tflite_path}.", flush=True)

    (
        input_shape,
        output_shape,
        input_scale,
        input_zero_point,
        output_scale,
        output_zero_point,
    ) = _inspect_tflite_io(tflite_path)

    metadata = build_export_metadata(
        source_model_path=config.model_path,
        tflite_path=tflite_path,
        input_shape=input_shape,
        output_shape=output_shape,
        input_scale=input_scale,
        input_zero_point=input_zero_point,
        output_scale=output_scale,
        output_zero_point=output_zero_point,
        representative_examples=len(representative_examples),
        hard_case_manifest=config.hard_case_manifest,
    )
    metadata_path = config.output_dir / "metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
    print(f"[EXPORT] Wrote metadata to {metadata_path}.", flush=True)

    return ExportResult(
        source_model_path=config.model_path,
        tflite_path=tflite_path,
        metadata_path=metadata_path,
        input_shape=input_shape,
        output_shape=output_shape,
        input_scale=input_scale,
        input_zero_point=input_zero_point,
        output_scale=output_scale,
        output_zero_point=output_zero_point,
        representative_examples=len(representative_examples),
    )
