"""Export utilities for turning gauge models into board artifacts."""

from __future__ import annotations

from dataclasses import dataclass
import faulthandler
import json
import os
from pathlib import Path
import time
from typing import Any, Iterable, Literal

# Keep export on CPU so TensorFlow does not stall on WSL GPU enumeration.
os.environ.setdefault("CUDA_VISIBLE_DEVICES", "-1")
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

import keras
import numpy as np
import tensorflow as tf

from embedded_gauge_reading_tinyml.dataset import load_dataset
from embedded_gauge_reading_tinyml.models import (
    GaugeValueFromKeypoints,
    SpatialSoftArgmax2D,
)
from embedded_gauge_reading_tinyml.gauge.processing import load_gauge_specs
from embedded_gauge_reading_tinyml.presets import (
    DEFAULT_CROP_PAD_RATIO,
    DEFAULT_GAUGE_ID,
    DEFAULT_IMAGE_HEIGHT,
    DEFAULT_IMAGE_WIDTH,
    DEFAULT_KEYPOINT_HEATMAP_SIZE,
)
from embedded_gauge_reading_tinyml.training import (
    LABELLED_DIR,
    RAW_DIR,
    TrainingExample,
    TrainConfig,
    _build_training_examples,
    _load_hard_case_examples,
    _load_rectifier_and_preprocess_image,
    _load_crop_and_preprocess_image,
    _split_examples,
)


@dataclass(frozen=True)
class ExportConfig:
    """Settings for the board export pipeline."""

    model_path: Path
    output_dir: Path
    hard_case_manifest: Path
    deployment_kind: Literal["scalar", "rectifier"] = "scalar"
    representative_count: int = 32
    image_height: int = DEFAULT_IMAGE_HEIGHT
    image_width: int = DEFAULT_IMAGE_WIDTH
    gauge_id: str = DEFAULT_GAUGE_ID
    crop_pad_ratio: float = DEFAULT_CROP_PAD_RATIO
    legacy_mobilenetv2_preprocess: bool = True


@dataclass(frozen=True)
class ExportResult:
    """Files and quantization details generated by export."""

    source_model_path: Path
    tflite_path: Path
    metadata_path: Path
    input_shape: tuple[int, ...]
    output_shape: tuple[int, ...]
    input_scale: float
    input_zero_point: int
    output_scale: float
    output_zero_point: int
    representative_examples: int


def _resolve_repo_path(path: Path, repo_root: Path) -> Path:
    """Resolve a relative repo path against the repository root."""
    if path.is_absolute():
        return path
    return repo_root / path


def _load_model(model_path: Path, *, legacy_mobilenetv2_preprocess: bool) -> keras.Model:
    """Load a saved Keras model artifact."""
    custom_objects: dict[str, Any] = {
        "preprocess_input": tf.keras.applications.mobilenet_v2.preprocess_input,
        "SpatialSoftArgmax2D": SpatialSoftArgmax2D,
        "GaugeValueFromKeypoints": GaugeValueFromKeypoints,
    }
    if legacy_mobilenetv2_preprocess:
        print("[EXPORT] Legacy MobileNetV2 preprocess support enabled.", flush=True)
    model = keras.models.load_model(
        model_path,
        custom_objects=custom_objects,
        compile=False,
    )
    print(f"[EXPORT] Loaded model '{model.name}' from {model_path}.", flush=True)
    return model


def _select_scalar_deployment_model(model: keras.Model) -> keras.Model:
    """Extract the scalar gauge-value output for deployment."""
    try:
        scalar_output = model.get_layer("gauge_value").output
    except ValueError:
        return model

    if len(model.outputs) == 1:
        return model

    scalar_model = keras.Model(
        inputs=model.inputs,
        outputs=scalar_output,
        name=f"{model.name}_scalar",
    )
    print(
        "[EXPORT] Using scalar deployment wrapper around multi-output model.",
        flush=True,
    )
    return scalar_model


def _build_representative_examples(
    *,
    hard_case_manifest: Path,
    image_height: int,
    image_width: int,
    representative_count: int,
    deployment_kind: Literal["scalar", "rectifier"],
) -> list[TrainingExample]:
    """Collect a deterministic slice of labeled images for TFLite calibration."""
    config = TrainConfig(
        image_height=image_height,
        image_width=image_width,
        crop_pad_ratio=DEFAULT_CROP_PAD_RATIO,
        keypoint_heatmap_size=DEFAULT_KEYPOINT_HEATMAP_SIZE,
        augment_training=False,
        hard_case_manifest=None,
        hard_case_repeat=0,
    )

    specs = load_gauge_specs()
    spec = specs[config.gauge_id]

    print("[EXPORT] Loading labelled dataset for representative examples...", flush=True)
    samples = load_dataset(labelled_dir=LABELLED_DIR, raw_dir=RAW_DIR)
    examples, dropped_out_of_sweep = _build_training_examples(
        samples,
        spec,
        strict_labels=config.strict_labels,
        crop_pad_ratio=config.crop_pad_ratio,
        image_height=config.image_height,
        image_width=config.image_width,
        keypoint_heatmap_size=config.keypoint_heatmap_size,
    )
    split = _split_examples(examples, config)
    example_lookup: dict[str, TrainingExample] = {
        str(example.image_path): example for example in examples
    }

    sorted_train_examples: list[TrainingExample] = sorted(
        split.train_examples,
        key=lambda example: example.value,
    )
    if representative_count >= len(sorted_train_examples):
        rep_train_examples = sorted_train_examples
    elif representative_count <= 0:
        rep_train_examples = []
    else:
        # Sample across the full label range so calibration sees extremes and midrange values.
        positions = np.linspace(
            0,
            len(sorted_train_examples) - 1,
            num=representative_count,
            dtype=np.float64,
        )
        selected_indices = sorted(
            {int(round(position)) for position in positions}
        )
        rep_train_examples = [
            sorted_train_examples[index] for index in selected_indices
        ]
    if deployment_kind == "rectifier":
        hard_case_examples = _load_hard_case_examples(
            hard_case_manifest,
            image_height=image_height,
            image_width=image_width,
            value_range=(spec.min_value, spec.max_value),
            target_kind="rectifier_box",
            example_lookup=example_lookup,
        )
    else:
        hard_case_examples = _load_hard_case_examples(
            hard_case_manifest,
            image_height=image_height,
            image_width=image_width,
            value_range=(spec.min_value, spec.max_value),
        )

    print(
        "[EXPORT] Representative data: "
        f"train={len(rep_train_examples)} "
        f"hard_cases={len(hard_case_examples)} "
        f"dropped_out_of_sweep={dropped_out_of_sweep}",
        flush=True,
    )
    return hard_case_examples + rep_train_examples


def _representative_dataset(
    examples: Iterable[TrainingExample],
    *,
    image_height: int,
    image_width: int,
) -> Iterable[list[np.ndarray]]:
    """Yield calibration images in the format TensorFlow Lite expects."""
    for example in examples:
        image, _ = _load_crop_and_preprocess_image(
            tf.convert_to_tensor(example.image_path, dtype=tf.string),
            tf.convert_to_tensor(example.value, dtype=tf.float32),
            tf.convert_to_tensor(example.crop_box_xyxy, dtype=tf.float32),
            image_height,
            image_width,
        )
        yield [np.expand_dims(image.numpy().astype(np.float32), axis=0)]


def _representative_dataset_rectifier(
    examples: Iterable[TrainingExample],
    *,
    image_height: int,
    image_width: int,
) -> Iterable[list[np.ndarray]]:
    """Yield full-frame calibration images for a rectifier deployment."""
    for example in examples:
        image, _ = _load_rectifier_and_preprocess_image(
            tf.convert_to_tensor(example.image_path, dtype=tf.string),
            tf.convert_to_tensor(example.crop_box_xyxy, dtype=tf.float32),
            image_height,
            image_width,
        )
        yield [np.expand_dims(image.numpy().astype(np.float32), axis=0)]


def _inspect_tflite_io(
    tflite_path: Path,
) -> tuple[tuple[int, ...], tuple[int, ...], float, int, float, int]:
    """Inspect the quantized input/output tensors of a TFLite model."""
    interpreter = tf.lite.Interpreter(model_path=str(tflite_path), num_threads=1)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    input_shape = tuple(int(value) for value in input_details["shape"])
    output_shape = tuple(int(value) for value in output_details["shape"])
    input_scale = float(input_details["quantization"][0])
    input_zero_point = int(input_details["quantization"][1])
    output_scale = float(output_details["quantization"][0])
    output_zero_point = int(output_details["quantization"][1])
    return (
        input_shape,
        output_shape,
        input_scale,
        input_zero_point,
        output_scale,
        output_zero_point,
    )


def build_export_metadata(
    *,
    source_model_path: Path,
    tflite_path: Path,
    input_shape: tuple[int, ...],
    output_shape: tuple[int, ...],
    input_scale: float,
    input_zero_point: int,
    output_scale: float,
    output_zero_point: int,
    representative_examples: int,
    hard_case_manifest: Path,
    deployment_kind: Literal["scalar", "rectifier"],
) -> dict[str, Any]:
    """Build a serializable metadata payload for firmware handoff."""
    return {
        "source_model_path": str(source_model_path),
        "tflite_path": str(tflite_path),
        "input_shape": list(input_shape),
        "output_shape": list(output_shape),
        "input_scale": input_scale,
        "input_zero_point": input_zero_point,
        "output_scale": output_scale,
        "output_zero_point": output_zero_point,
        "representative_examples": representative_examples,
        "hard_case_manifest": str(hard_case_manifest),
        "board_input_size": {
            "height": int(input_shape[1]) if len(input_shape) > 1 else None,
            "width": int(input_shape[2]) if len(input_shape) > 2 else None,
        },
        "board_notes": (
            "Use this artifact with the STM32 capture path that already crops to "
            "224x224 and preserves gauge geometry."
            if deployment_kind == "scalar"
            else "Use this artifact as the first-stage rectifier on the STM32 "
            "capture path. It consumes the full frame and predicts a dial crop."
        ),
    }


def export_board_tflite_artifacts(config: ExportConfig) -> ExportResult:
    """Export a board CNN into an int8 TFLite bundle."""
    config.output_dir.mkdir(parents=True, exist_ok=True)

    start_time = time.monotonic()
    faulthandler.dump_traceback_later(300.0, repeat=False)
    try:
        print("[EXPORT] Stage: load-model", flush=True)
        model = _load_model(
            config.model_path,
            legacy_mobilenetv2_preprocess=config.legacy_mobilenetv2_preprocess,
        )
        if config.deployment_kind == "scalar":
            model = _select_scalar_deployment_model(model)
        print(
            f"[EXPORT] Stage: load-model-done elapsed={time.monotonic() - start_time:.1f}s",
            flush=True,
        )

        print("[EXPORT] Stage: build-representative-examples", flush=True)
        representative_examples = _build_representative_examples(
            hard_case_manifest=config.hard_case_manifest,
            image_height=config.image_height,
            image_width=config.image_width,
            representative_count=config.representative_count,
            deployment_kind=config.deployment_kind,
        )
        print(
            "[EXPORT] Stage: build-representative-examples-done "
            f"elapsed={time.monotonic() - start_time:.1f}s",
            flush=True,
        )

        print("[EXPORT] Stage: convert-to-int8", flush=True)
        print("[EXPORT] Converting model to fully quantized int8 TFLite...", flush=True)
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
        if config.deployment_kind == "rectifier":
            converter.representative_dataset = lambda: _representative_dataset_rectifier(
                representative_examples,
                image_height=config.image_height,
                image_width=config.image_width,
            )
        else:
            converter.representative_dataset = lambda: _representative_dataset(
                representative_examples,
                image_height=config.image_height,
                image_width=config.image_width,
            )
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.int8
        converter.inference_output_type = tf.int8
        tflite_model: bytes = converter.convert()

        tflite_path = config.output_dir / "model_int8.tflite"
        tflite_path.write_bytes(tflite_model)
        print(f"[EXPORT] Wrote TFLite model to {tflite_path}.", flush=True)

        (
            input_shape,
            output_shape,
            input_scale,
            input_zero_point,
            output_scale,
            output_zero_point,
        ) = _inspect_tflite_io(tflite_path)

        metadata = build_export_metadata(
            source_model_path=config.model_path,
            tflite_path=tflite_path,
            input_shape=input_shape,
            output_shape=output_shape,
            input_scale=input_scale,
            input_zero_point=input_zero_point,
            output_scale=output_scale,
            output_zero_point=output_zero_point,
            representative_examples=len(representative_examples),
            hard_case_manifest=config.hard_case_manifest,
            deployment_kind=config.deployment_kind,
        )
        metadata["deployment_kind"] = config.deployment_kind
        metadata_path = config.output_dir / "metadata.json"
        metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")
        print(f"[EXPORT] Wrote metadata to {metadata_path}.", flush=True)

        return ExportResult(
            source_model_path=config.model_path,
            tflite_path=tflite_path,
            metadata_path=metadata_path,
            input_shape=input_shape,
            output_shape=output_shape,
            input_scale=input_scale,
            input_zero_point=input_zero_point,
            output_scale=output_scale,
            output_zero_point=output_zero_point,
            representative_examples=len(representative_examples),
        )
    finally:
        faulthandler.cancel_dump_traceback_later()
