# File automatically-generated by STM32CubeMX - Do not modify
set(ST_MULTICONTEXT TRUST_ZONE CACHE STRING "Type of multi-context")
#-----------------------Build AppliSecure Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*AppliSecure.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " AppliSecure)
    ExternalProject_Add(n657_bringup_AppliSecure
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/AppliSecure/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/AppliSecure
        PREFIX                      AppliSecure
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/AppliSecure/build")
	set(ST_TRUST_ZONE_APPLISECURE_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/AppliSecure/build/n657_bringup_AppliSecure${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to applisecure project target")
endif()
#-----------------------Build FSBL Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*FSBL.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " FSBL)
    ExternalProject_Add(n657_bringup_FSBL
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/FSBL/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/FSBL
        PREFIX                      FSBL
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/FSBL/build")
	set(ST_BOOT_FLASH_FSBL_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/FSBL/build/n657_bringup_FSBL${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to fsbl project target")
endif()
#-----------------------Build AppliNonSecure Project-----------------------#
if((${BUILD_CONTEXT} MATCHES .*AppliNonSecure.*) OR (NOT DEFINED BUILD_CONTEXT))
    message("   Build context: " AppliNonSecure)
    ExternalProject_Add(n657_bringup_AppliNonSecure
        BINARY_DIR                  ${CMAKE_SOURCE_DIR}/AppliNonSecure/build
        SOURCE_DIR                  ${PROJECT_SOURCE_DIR}/AppliNonSecure
        PREFIX                      AppliNonSecure
        CONFIGURE_HANDLED_BY_BUILD  true
        INSTALL_COMMAND             ""
        CMAKE_ARGS                  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}  -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        BUILD_ALWAYS                true
        DEPENDS                     n657_bringup_AppliSecure
    )

	set_property(DIRECTORY APPEND PROPERTY ADDITIONAL_CLEAN_FILES "${CMAKE_SOURCE_DIR}/AppliNonSecure/build")
	set(ST_TRUST_ZONE_APPLINONSECURE_PROJECT_BUILD_TARGET ${CMAKE_SOURCE_DIR}/AppliNonSecure/build/n657_bringup_AppliNonSecure${CMAKE_EXECUTABLE_SUFFIX_CXX} CACHE FILEPATH "Path to applinonsecure project target")
endif()

