/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    app_center_detector.c
  * @brief   Centre-detector NPU model + polar-vote temperature estimation.
  *
  * Replaces the scalar-CNN path.  The OBB stage detects the gauge crop, then
  * this module runs the centre-detector model on the NPU, decodes the
  * normalised (cx, cy) pivot, and passes it to the CPU polar-vote detector
  * (from app_baseline_runtime) for the final needle angle → temperature.
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "app_center_detector.h"

#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "app_ai.h"
#include "app_baseline_runtime.h"
#include "app_gauge_geometry.h"
#include "debug_console.h"
#include "ll_aton.h"
#include "ll_aton_rt_user_api.h"
#include "ll_aton_runtime.h"
#include "npu_cache.h"
#include "stm32n6xx_nucleo_xspi.h"

/* The Cube.AI-generated network code.  Include the thin wrapper which in
 * turn includes the autogenerated mobilenetv2_center_detector.c.
 * These symbols are created by STM32Cube.AI when the centre-detector
 * model_int8.tflite is imported with network name "mobilenetv2_center_detector".
 */
#include "ai_network_mobilenetv2_center_detector.h"

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */
/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/** @brief Number of full-resolution camera frame bytes for the polar vote. */
#define APP_CD_CAMERA_WIDTH_PX     2592U
#define APP_CD_CAMERA_HEIGHT_PX    1944U
#define APP_CD_CAMERA_BYTES_PER_PX 2U
#define APP_CD_FRAME_BYTES \
    (APP_CD_CAMERA_WIDTH_PX * APP_CD_CAMERA_HEIGHT_PX * APP_CD_CAMERA_BYTES_PER_PX)

/** @brief Dial radius in full-frame pixels (0.56 × crop_height). */
#define APP_CD_FULL_FRAME_DIAL_RADIUS_PX \
    (0.56f * (float)APP_CD_CAMERA_HEIGHT_PX)

/** @brief Scan region radius around the centre for the polar vote. */
#define APP_CD_POLAR_SCAN_RADIUS_FACTOR 1.8f

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */
/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN PV */

/** @brief Memory pool placeholder linked to the xSPI2 flash section. */
__attribute__((section(".xspi2_center_detector_pool"), aligned(32)))
static uint8_t _mem_pool_xSPI2_mobilenetv2_center_detector[32U] = {0U};

/** @brief Whether the centre-detector NPU model has been initialised. */
static bool _cd_initialised = false;

/** @brief The centre-detector model stage spec (matches app_ai.c pattern). */
static const AppAI_ModelStageSpec _cd_stage = {
    .stage_label = "center_detector",
    .model_image_path = APP_AI_CENTER_DETECTOR_XSPI2_MODEL_IMAGE_PATH,
    .nn_instance = &NN_Instance_mobilenetv2_center_detector,
    .network_init_fn = LL_ATON_EC_Network_Init_mobilenetv2_center_detector,
    .inference_init_fn = LL_ATON_EC_Inference_Init_mobilenetv2_center_detector,
    .uses_rectifier_box = false,
    .xspi2_chip_offset = APP_AI_XSPI2_CENTER_DETECTOR_CHIP_OFFSET,
    .xspi2_base_addr = APP_AI_XSPI2_CENTER_DETECTOR_BASE_ADDR,
};

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN PFP */

/**
 * @brief Resample a sub-rectangle of the full YUV422 frame to 224×224 int8 RGB
 *        using simple area-average downscaling, then quantise to int8.
 *
 * @param frame_bytes    Full YUV422 frame (2592×1944×2).
 * @param frame_size     Size of frame_bytes in bytes.
 * @param src_x, src_y   Top-left of source region (full-frame coords).
 * @param src_w, src_h   Size of source region (full-frame coords).
 * @param dst            Output buffer: 224×224×3 int8 (row-major RGB).
 * @param dst_cx_out     Output buffer X stride (bytes per pixel row).
 */
static void _cd_resample_crop_to_int8(
    const uint8_t *frame_bytes, size_t frame_size,
    size_t src_x, size_t src_y,
    size_t src_w, size_t src_h,
    int8_t *dst);

/**
 * @brief Decode the int8 model output to normalised (cx, cy) in [0, 1].
 *
 * The centre-detector model outputs 2 int8 values.  Quantisation is:
 *   float_value = (int8_value - zero_point) * scale
 * where scale = 0.00390625 and zero_point = -128 (from metadata.json).
 *
 * @param output_bytes  Pointer to the raw int8 output buffer (2 bytes).
 * @param cx_out        Receives normalised centre X in [0, 1].
 * @param cy_out        Receives normalised centre Y in [0, 1].
 */
static void _cd_decode_output(
    const int8_t *output_bytes,
    float *cx_out,
    float *cy_out);

/**
 * @brief Convert a crop-space (cx, cy) to full-frame pixel coordinates.
 */
static void _cd_crop_to_full_frame(
    size_t crop_x_min, size_t crop_y_min,
    size_t crop_width, size_t crop_height,
    float crop_cx, float crop_cy,
    size_t *full_cx_out, size_t *full_cy_out);

/* USER CODE END PFP */

/* Exported functions --------------------------------------------------------*/

bool AppCenterDetector_IsAvailable(void)
{
    return _cd_initialised;
}

void AppCenterDetector_Deinit(void)
{
    _cd_initialised = false;
}

bool AppCenterDetector_RunPipeline(
    const uint8_t *frame_bytes, size_t frame_size,
    size_t crop_x_min, size_t crop_y_min,
    size_t crop_width, size_t crop_height,
    float *temperature_c_out,
    float *confidence_out,
    float *angle_deg_out)
{
    /* Validate inputs. */
    if ((frame_bytes == NULL) || (frame_size < APP_CD_FRAME_BYTES) ||
        (temperature_c_out == NULL) || (confidence_out == NULL) ||
        (angle_deg_out == NULL))
    {
        return false;
    }

    /* Guard against degenerate crop regions. */
    if ((crop_width < 8U) || (crop_height < 8U))
    {
        DebugConsole_Printf(
            "[CD] Degenerate crop: %lu x %lu\r\n",
            (unsigned long)crop_width, (unsigned long)crop_height);
        return false;
    }

    /* ── 1. Ensure NPU model is ready ─────────────────────────────────── */
    if (!_cd_initialised)
    {
        DebugConsole_WriteString("[CD] Initialising centre-detector model...\r\n");

        /* Ensure xSPI2 is in memory-mapped mode. */
        if (!AppAI_Xspi2EnsureMemoryMappedMode())
        {
            DebugConsole_WriteString("[CD] xSPI2 memory-mapped mode failed.\r\n");
            return false;
        }

        /* Verify the stage's xSPI2 flash signature. */
        if (!AppAI_Xspi2ReadStageProbe(&_cd_stage))
        {
            DebugConsole_WriteString(
                "[CD] xSPI2 signature mismatch — model not programmed.\r\n");
            return false;
        }

        /* Run the network init (loads model metadata from flash). */
        if (!_cd_stage.network_init_fn())
        {
            DebugConsole_WriteString("[CD] Network init failed.\r\n");
            return false;
        }
        LL_ATON_RT_Init_Network(_cd_stage.nn_instance);

        /* Run the inference init (allocates scratch buffers). */
        if (!_cd_stage.inference_init_fn())
        {
            DebugConsole_WriteString("[CD] Inference init failed.\r\n");
            LL_ATON_RT_DeInit_Network(_cd_stage.nn_instance);
            return false;
        }

        _cd_initialised = true;
        DebugConsole_WriteString("[CD] Centre-detector model ready.\r\n");
    }

    /* ── 2. Preprocess: crop + resize + quantise ──────────────────────── */
    int8_t cd_input[APP_CENTER_DETECTOR_INPUT_SIZE];
    _cd_resample_crop_to_int8(
        frame_bytes, frame_size,
        crop_x_min, crop_y_min, crop_width, crop_height,
        cd_input);

    /* ── 3. Write input buffer, run NPU inference ─────────────────────── */
    {
        const LL_Buffer_InfoTypeDef *input_info =
            _cd_stage.nn_instance->network->input_buffers_info();
        if ((input_info == NULL) || (input_info->name == NULL))
        {
            DebugConsole_WriteString("[CD] No input buffer info.\r\n");
            return false;
        }

        const size_t input_buffer_bytes =
            (size_t)LL_Buffer_GetBufferInfo(input_info->next ?
                (input_info->next - input_info) : 1U, input_info)->size;
        if (input_buffer_bytes < sizeof(cd_input))
        {
            DebugConsole_WriteString("[CD] Input buffer too small.\r\n");
            return false;
        }

        int8_t *input_ptr = (int8_t *)LL_Buffer_addr_start(input_info);
        if (input_ptr == NULL)
        {
            DebugConsole_WriteString("[CD] Input buffer addr is NULL.\r\n");
            return false;
        }

        memcpy(input_ptr, cd_input, sizeof(cd_input));
        mcu_cache_clean_range(
            (uint32_t)input_ptr,
            (uint32_t)(input_ptr + sizeof(cd_input)));

        /* ── Run inference ────────────────────────────────────────────── */
        {
            uint32_t num_epochs = 0U;
            LL_ATON_RT_Return_Type run_status;

            AppAI_Xspi2EnsureMemoryMappedMode();

            do {
                run_status = LL_ATON_RT_RunEpochBlock(
                    _cd_stage.nn_instance);
                if (run_status == LL_ATON_RT_DONE)
                {
                    break;
                }
                if (run_status == LL_ATON_RT_WFE)
                {
                    LL_ATON_OSAL_WFE();
                }
                /* LL_ATON_RT_NO_WFE → continue polling */
                ++num_epochs;
            } while (num_epochs < 1000U);

            if (run_status != LL_ATON_RT_DONE)
            {
                DebugConsole_Printf(
                    "[CD] Inference failed: status=%d epochs=%lu\r\n",
                    (int)run_status, (unsigned long)num_epochs);
                return false;
            }
        }

        /* ── 4. Read output buffer and decode ─────────────────────────── */
        const LL_Buffer_InfoTypeDef *output_info =
            _cd_stage.nn_instance->network->output_buffers_info();
        if ((output_info == NULL) || (output_info->name == NULL))
        {
            DebugConsole_WriteString("[CD] No output buffer info.\r\n");
            return false;
        }

        const size_t output_buffer_bytes =
            (size_t)LL_Buffer_GetBufferInfo(output_info->next ?
                (output_info->next - output_info) : 1U, output_info)->size;
        if (output_buffer_bytes < APP_CENTER_DETECTOR_OUTPUT_SIZE)
        {
            DebugConsole_WriteString("[CD] Output buffer too small.\r\n");
            return false;
        }

        const int8_t *output_ptr =
            (const int8_t *)LL_Buffer_addr_start(output_info);
        if (output_ptr == NULL)
        {
            DebugConsole_WriteString("[CD] Output buffer addr is NULL.\r\n");
            return false;
        }

        mcu_cache_invalidate_range(
            (uint32_t)output_ptr,
            (uint32_t)(output_ptr + APP_CENTER_DETECTOR_OUTPUT_SIZE));

        float cd_cx_norm = 0.0f, cd_cy_norm = 0.0f;
        _cd_decode_output(output_ptr, &cd_cx_norm, &cd_cy_norm);

        /* ── 5. Convert crop-space centre to full-frame coords ────────── */
        size_t full_cx = 0U, full_cy = 0U;
        _cd_crop_to_full_frame(
            crop_x_min, crop_y_min, crop_width, crop_height,
            cd_cx_norm, cd_cy_norm,
            &full_cx, &full_cy);

        DebugConsole_Printf(
            "[CD] Centre: crop=(%.3f,%.3f) full=(%lu,%lu)\r\n",
            (double)cd_cx_norm, (double)cd_cy_norm,
            (unsigned long)full_cx, (unsigned long)full_cy);

        /* ── 6. Run CPU polar-vote at the predicted centre ────────────── */
        {
            const size_t scan_radius = (size_t)(
                APP_CD_FULL_FRAME_DIAL_RADIUS_PX *
                APP_CD_POLAR_SCAN_RADIUS_FACTOR);

            const size_t scan_x_min = (full_cx > scan_radius) ?
                (full_cx - scan_radius) : 0U;
            const size_t scan_y_min = (full_cy > scan_radius) ?
                (full_cy - scan_radius) : 0U;
            const size_t scan_x_max = (full_cx + scan_radius <
                APP_CD_CAMERA_WIDTH_PX) ?
                (full_cx + scan_radius) : APP_CD_CAMERA_WIDTH_PX;
            const size_t scan_y_max = (full_cy + scan_radius <
                APP_CD_CAMERA_HEIGHT_PX) ?
                (full_cy + scan_radius) : APP_CD_CAMERA_HEIGHT_PX;

            /* The polar vote returns temperature, angle, and confidence.
             * We use a new public wrapper exposed by app_baseline_runtime. */
            if (!AppBaseline_RunPolarVoteAtPoint(
                    frame_bytes, frame_size,
                    full_cx, full_cy,
                    APP_CD_FULL_FRAME_DIAL_RADIUS_PX,
                    scan_x_min, scan_y_min, scan_x_max, scan_y_max,
                    angle_deg_out,
                    temperature_c_out,
                    confidence_out))
            {
                DebugConsole_Printf(
                    "[CD] Polar vote failed at centre (%lu,%lu).\r\n",
                    (unsigned long)full_cx, (unsigned long)full_cy);
                return false;
            }

            DebugConsole_Printf(
                "[CD] Result: angle=%.1f° temp=%.1f°C "
                "confidence=%.1f\r\n",
                (double)*angle_deg_out,
                (double)*temperature_c_out,
                (double)*confidence_out);
        }
    }

#if APP_AI_RESET_NETWORK_EACH_INFERENCE
    LL_ATON_RT_Reset_Network(_cd_stage.nn_instance);
#endif

    return true;
}

/* Private functions ---------------------------------------------------------*/

static void _cd_resample_crop_to_int8(
    const uint8_t *frame_bytes, size_t frame_size,
    size_t src_x, size_t src_y,
    size_t src_w, size_t src_h,
    int8_t *dst)
{
    /* Clamp source region to frame bounds. */
    if (src_x + src_w > APP_CD_CAMERA_WIDTH_PX)
    {
        src_w = APP_CD_CAMERA_WIDTH_PX - src_x;
    }
    if (src_y + src_h > APP_CD_CAMERA_HEIGHT_PX)
    {
        src_h = APP_CD_CAMERA_HEIGHT_PX - src_y;
    }
    if ((src_w == 0U) || (src_h == 0U))
    {
        return;
    }

    const size_t dst_w = APP_CENTER_DETECTOR_CROP_WIDTH_PIXELS;
    const size_t dst_h = APP_CENTER_DETECTOR_CROP_HEIGHT_PIXELS;

    /* Simple area-averaged downscale using integer stepping.
     * YUV422 byte layout per pixel: [Y, U or V] alternating.
     * We extract Y as luma and set R=G=B=Y (grayscale) for the NPU,
     * which matches the training pipeline (MobileNetV2 input). */
    for (size_t dy = 0U; dy < dst_h; ++dy)
    {
        const size_t sy = src_y + (dy * src_h) / dst_h;
        for (size_t dx = 0U; dx < dst_w; ++dx)
        {
            const size_t sx = src_x + (dx * src_w) / dst_w;

            /* YUV422: Y at byte offset 0, U/V at offset 1.
             * Using the Y component only (grayscale). */
            const size_t src_idx = (sy * APP_CD_CAMERA_WIDTH_PX + sx) *
                APP_CD_CAMERA_BYTES_PER_PX;
            const uint8_t y_val = (src_idx < frame_size) ?
                frame_bytes[src_idx] : 0U;

            /* Quantise to int8: input_scale=0.003921569, zp=-128.
             * int8 = round(float / scale) + zp
             * float = y_val / 255.0 (normally [0,1] input,
             *                      but model has its own rescaling) */
            const float y_norm = (float)y_val / 255.0f;
            const int32_t q = (int32_t)roundf(
                y_norm / 0.003921568859368563f) + (-128);
            const int8_t q_clamped = (int8_t)((q < -128) ? -128 :
                                             ((q > 127) ? 127 : q));

            const size_t dst_idx = (dy * dst_w + dx) *
                APP_CENTER_DETECTOR_BYTES_PER_PIXEL;
            dst[dst_idx + 0] = q_clamped; /* R */
            dst[dst_idx + 1] = q_clamped; /* G */
            dst[dst_idx + 2] = q_clamped; /* B */
        }
    }
}

static void _cd_decode_output(
    const int8_t *output_bytes,
    float *cx_out,
    float *cy_out)
{
    /* Quantisation from metadata.json:
     *   output_scale = 0.00390625
     *   output_zero_point = -128
     *   float = (int8 - zero_point) * scale
     */
    const float scale = 0.00390625f;
    const float zp = -128.0f;

    *cx_out = ((float)output_bytes[0] - zp) * scale;
    *cy_out = ((float)output_bytes[1] - zp) * scale;

    /* Clamp to [0, 1] — the model was trained with sigmoid activation. */
    if (*cx_out < 0.0f) *cx_out = 0.0f;
    if (*cx_out > 1.0f) *cx_out = 1.0f;
    if (*cy_out < 0.0f) *cy_out = 0.0f;
    if (*cy_out > 1.0f) *cy_out = 1.0f;
}

static void _cd_crop_to_full_frame(
    size_t crop_x_min, size_t crop_y_min,
    size_t crop_width, size_t crop_height,
    float crop_cx, float crop_cy,
    size_t *full_cx_out, size_t *full_cy_out)
{
    /* The centre detector outputs (cx, cy) normalised to [0, 1] in the
     * 224×224 crop space.  We map back to full-frame pixels via:
     *   full_x = crop_x_min + cx * crop_width
     *   full_y = crop_y_min + cy * crop_height
     */
    const float full_cx_f =
        (float)crop_x_min + crop_cx * (float)crop_width;
    const float full_cy_f =
        (float)crop_y_min + crop_cy * (float)crop_height;

    /* Round to nearest integer and clamp to valid range. */
    long cx_long = (long)roundf(full_cx_f);
    long cy_long = (long)roundf(full_cy_f);

    if (cx_long < 0L) cx_long = 0L;
    if (cx_long >= (long)APP_CD_CAMERA_WIDTH_PX)
        cx_long = (long)APP_CD_CAMERA_WIDTH_PX - 1L;
    if (cy_long < 0L) cy_long = 0L;
    if (cy_long >= (long)APP_CD_CAMERA_HEIGHT_PX)
        cy_long = (long)APP_CD_CAMERA_HEIGHT_PX - 1L;

    *full_cx_out = (size_t)cx_long;
    *full_cy_out = (size_t)cy_long;
}
